#!/usr/bin/env bash
#
# Use this as a model for a new test file, and replace every BLANK keyword.


#-------------------------------------------------------------------------------
# ::init
#
test::init() {

	# Change to the directory where this script is located
	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
		cd -- "${BASH_SOURCE%/*}" || exit 1
	fi

	# shellcheck disable=SC1091
	source ./helper &>/dev/null

	# Run tests
	test_setup
	test::suite
	test_teardown

	test_summary "BLANK"

} #::init()


#-------------------------------------------------------------------------------
# ::suite
#
test::suite() {

	test_h1 "BLANK"
	# ========================


	test_h2 "BLANK h2"
	# ~~~~~~~~~~~~~~~~~~~~~~~~

	test_clean


	test_h3 "BLANK h3"
	# ------------------------

	test_clean


	# T: test_example 1
	assert_success "true"

	# T: test_example 2
	assert_failure "false"






} #::suite()


[[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
