#!/usr/bin/env bash

# change to the directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

# find all tests and run them one by one
TESTS=$(find . -maxdepth 1 -name "test-*.bats" -type f | tr '\n' ' ')

for T in $TESTS; do
	printf "\nrunning '$T'. . .\n\n"
	bats $T
done
