#!/usr/bin/env bash


# ::suite
#
#   Test the test helper functions.
#
test::suite() {

	test_h1 "Helper Functions"
	# ========================


	test_h2 "test_setup()"
	# ~~~~~~~~~~~~~~~~~~~~~~~~


	local originalDir
	originalDir=$(pwd)


	test_setup


	local workDir
	workDir=$(pwd)

	# T: we are now in a different directory
	assert_success "[[ $workDir != $originalDir ]]"

	# T: we are also in the workdir directory
	assert_success "pwd | grep -E --silent 'webera-test-[a-zA-Z0-9]{9}$'"

	# T: it is empty
	assert "ls -a" ".\n.."

	# T: we can create files
	touch test_file
	assert_success "ls test_file"


	test_h2 "test_clean()"
	# ~~~~~~~~~~~~~~~~~~~~~~~~


	test_clean


	# T: we should still be in the same directory
	assert_success "[[ $workDir == $(pwd) ]]"

	# T: previously created file shouldn't exist
	assert_success "[[ ! -f test_file ]]"

	# T: directory should be empty
	assert "ls -a" ".\n.."


	test_h2 "test_teardown()"
	# ~~~~~~~~~~~~~~~~~~~~~~~~


	test_teardown


	# T: We are not anymore in the working directory
	assert_success "[[ $workDir != $originalDir ]]"

	# T: We are back to the original dir
	assert_success "[[ $originalDir == $(pwd) ]]"

	# T: Temporary directory doesn't exist anymore
	assert_success "[[ ! -d $workDir ]]"


} #::suite()


#-------------------------------------------------------------------------------
# ::init
#
# > $1 : if equals "RUN_ALL_TESTS" then don't do final cleanup
#
test::init() {

	# Change to the directory where this script is located
	if [[ "${BASH_SOURCE%/*}" != "${BASH_SOURCE[0]}" ]]; then
		cd -- "${BASH_SOURCE%/*}" || exit 1
	fi

	# shellcheck disable=SC1091
	source ./helper &>/dev/null

	# Run tests
	#
	# NOTE: calls to `test_setup` and `test_teardown` are included in the suite
	test::suite

	test_summary "helper"

	# Only do the final cleanup when the script is run independently
	[[ $1 != RUN_ALL_TESTS ]] && test_final_cleanup

} #::init()


[[ "$0" == "${BASH_SOURCE[0]}" ]] && test::init "$@"
