#!/usr/bin/env bash

DEBUG=0
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEBERA="$DIR/../webera"
LOGFILE="$DIR/examples-generated.log"
OUTPUT="$DIR/../docs"

usage() {
	cat << ENDHERE

Usage: ./generate-examples.sh [--preview]

Pass `--preview` to open in default browser
ENDHERE
	exit 1
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
	usage
fi

cd $DIR

case "$1" in
	"--preview")
		PREVIEW=true;;
	"")
		;;
	*)
		usage;;
esac

EXAMPLES=$(find . -maxdepth 1 -type d | cut -d'/' -f2 | grep -v '^\.\+$' | sort | tac | tr '\n' ' ')

for E in $EXAMPLES; do
	cd $E;

	printf "generating '$E'. . . \n"

	$WEBERA -rt -L${DEBUG} -G $LOGFILE

	cd $DIR
done

printf "\nDone.\n"

if [ $PREVIEW ]; then
	$WEBERA -wO "$OUTPUT"
fi
