#!/usr/bin/env bash

main() {
	local OPTION_LOG_LEVEL=0
	local OPTION_LOG_CLEAR=''
	local OPTION_LOAD_IN_WEB_BROWSER=false;

	local DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	local WEBERA="$DIR/../webera"
	local LOGFILE="$DIR/examples.log"
	local OUTPUT="$DIR/../docs"

	parseArguments "$@"

	generateExamples

	printf "\nDone.\n"

	if [ "$OPTION_LOAD_IN_WEB_BROWSER" = true ]; then
		$WEBERA -wO "$OUTPUT"
	fi
}

usage() {
	cat <<- ENDUSAGE

	Generates every example.

	Usage: ./generate-examples [OPTIONS]

	  -w              preview in web browser
	  -L <NUMBER>     log level [0=none|1|2|3] ($OPTION_LOG_LEVEL)
	  -c              switch clearing the log file (clear=$OPTION_CLEAR_LOG)
	ENDUSAGE
	exit 1
}

parseArguments() {
	local OPTIND OPTION
	while getopts 'wL:ch' OPTION; do

		case "$OPTION" in
			w) OPTION_LOAD_IN_WEB_BROWSER=true ;;
			L) OPTION_LOG_LEVEL="$OPTARG" ;;
			c) OPTION_LOG_CLEAR=true ;;
			h|*) usage; exit ;;
		esac
	done
}

generateExamples() {

	cd $DIR

	[[ "$OPTION_LOG_CLEAR" == true ]] && rm "$LOGFILE"

	local EXAMPLES=$(find . -maxdepth 1 -type d \
		| cut -d'/' -f2 \
		| grep -v '^\.\+$' \
		| sort | tac | \
		tr '\n' ' ')

	for E in $EXAMPLES; do
		cd $E;

		printf "generating '$E'. . . \n"

		$WEBERA -rt -L${OPTION_LOG_LEVEL} -G $LOGFILE

		cd $DIR
	done
}

main "$@"
